chore: update ec2 instance IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,23 +32,22 @@ jobs:
           ssh -o StrictHostKeyChecking=no $USER@$HOST "
             set -e
             echo 'Starting deployment...'
-            export NVM_DIR=\"$HOME/.nvm\" &&
-            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" ||
-            { echo 'NVM not found or could not be loaded'; exit 1; }
+            export NVM_DIR=\"$HOME/.nvm\"
+            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" || { echo 'NVM not found or could not be loaded'; exit 1; }
+            nvm install 20
             nvm use 20
             echo 'Navigating to application directory...'
             cd $PATH_TO_APP
             echo 'Fetching latest changes...'
             git fetch origin &&
-            git reset --hard origin/main ||
-            { echo 'Git fetch or reset failed'; exit 1; }
+            git reset --hard origin/main
             echo 'Installing dependencies...'
-            npm ci || { echo 'npm ci failed'; exit 1; }
-            npm install -g pm2 || { echo 'pm2 installation failed'; exit 1; }
+            npm ci
+            npm install -g pm2
             echo 'Building project...'
-            npm run build || { echo 'Build failed'; exit 1; }
+            npm run build
             echo 'Restarting PM2...'
             pm2 flush
-            pm2 restart all || { echo 'PM2 restart failed'; exit 1; }
+            pm2 restart all
             echo 'Deployment completed successfully.'
           "
