chore: update ec2 instance IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,15 +30,25 @@ jobs:
           PATH_TO_APP: /home/ubuntu/app/desafio-votacao-pautas/
         run: |
           ssh -o StrictHostKeyChecking=no $USER@$HOST "
+            set -e
+            echo 'Starting deployment...'
             export NVM_DIR=\"$HOME/.nvm\" &&
-            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" &&
-            nvm use 20 &&
-            cd $PATH_TO_APP &&
+            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" ||
+            { echo 'NVM not found or could not be loaded'; exit 1; }
+            nvm use 20
+            echo 'Navigating to application directory...'
+            cd $PATH_TO_APP
+            echo 'Fetching latest changes...'
             git fetch origin &&
-            git reset --hard origin/main &&
-            npm ci && # Usa 'npm ci' para uma instalação limpa baseada no package-lock.json
-            npm install -g pm2 &&
-            npm run build &&
-            pm2 flush &&
-            pm2 restart all
+            git reset --hard origin/main ||
+            { echo 'Git fetch or reset failed'; exit 1; }
+            echo 'Installing dependencies...'
+            npm ci || { echo 'npm ci failed'; exit 1; }
+            npm install -g pm2 || { echo 'pm2 installation failed'; exit 1; }
+            echo 'Building project...'
+            npm run build || { echo 'Build failed'; exit 1; }
+            echo 'Restarting PM2...'
+            pm2 flush
+            pm2 restart all || { echo 'PM2 restart failed'; exit 1; }
+            echo 'Deployment completed successfully.'
           "
